### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by anthonydevaux** [RGLab/scamp#1]
Hello,

I would like to try your package but I have some issues to install it from its source. I already install devtools and Rtools but it doesn't work. I also tried to install it on another computer but same issue. I work with R 3.5.1

Thanks for your help.

Anthony

---------------------------------------------------------------------------------------------
> devtools::session_info()
Session info ------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.5.1 (2018-07-02)
 system   x86_64, mingw32             
 ui       RStudio (1.1.442)           
 language (EN)                        
 collate  French_France.1252          
 tz       Europe/Paris                
 date     2018-07-30

**Comment by evangreene** [comment]
Hi Anthony,

Would you mind posting the error message you're receiving from devtools when you try to install the package?

Thanks,
Evan

**Comment by anthonydevaux** [comment]
Hi Evan,

Thanks for your reply. You can see below the error message I have from the installation.

Thanks,
Anthony

-------------------------------------------------------------------------------------------------
> library(devtools)
> devtools::install_github("RGLab/scamp")
Downloading GitHub repo RGLab/scamp@master
from URL https://api.github.com/repos/RGLab/scamp/zipball/master
Installing scamp
"C:/PROGRA~1/R/R-35~1.1/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  "C:/Users/ad12/AppData/Local/Temp/RtmpqGSczo/devtools6c01d1a3c24/RGLab-scamp-2c5f1d8"  \
  --library="C:/Users/ad12/Documents/R/win-library/3.5" --install-tests 

* installing *source* package 'scamp' ...
** libs

*** arch - i386
c:/Rtools/mingw_32/bin/g++  -I"C:/PROGRA~1/R/R-35~1.1/include" -DNDEBUG  -I"C:/Users/ad12/Documents/R/win-library/3.5/Rcpp/include"     -std=c++11   -O2 -Wall  -mtune=generic -c RcppExports.cpp -o RcppExports.o
c:/Rtools/mingw_32/bin/g++  -I"C:/PROGRA~1/R/R-35~1.1/include" -DNDEBUG  -I"C:/Users/ad12/Documents/R/win-library/3.5/Rcpp/include"     -std=c++11   -O2 -Wall  -mtune=generic -c absSampleLmoments.cpp -o absSampleLmoments.o
absSampleLmoments.cpp: In function 'std::vector<double> absSampleLmoments(std::vector<double>, int, int)':
absSampleLmoments.cpp:75:22: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (auto i = 0; i != tmpDV.size(); ++i) 
                      ^
absSampleLmoments.cpp:83:24: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (auto i = 0; i != legendrePoly.size(); ++i)  {
                        ^
absSampleLmoments.cpp:108:25: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       for (int r = 1; r != (lMoments.size() - 1); ++r) {
                         ^
absSampleLmoments.cpp:116:22: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (auto i = 0; i != lMoments.size(); ++i)
                      ^
c:/Rtools/mingw_32/bin/g++  -I"C:/PROGRA~1/R/R-35~1.1/include" -DNDEBUG  -I"C:/Users/ad12/Documents/R/win-library/3.5/Rcpp/include"     -std=c++11   -O2 -Wall  -mtune=generic -c addNoiseToDataMatrix.cpp -o addNoiseToDataMatrix.o
addNoiseToDataMatrix.cpp:24:26: fatal error: sys/resource.h: No such file or directory
 #include <sys/resource.h>
                          ^
compilation terminated.
make: *** [addNoiseToDataMatrix.o] Error 1
ERROR: compilation failed for package 'scamp'
* removing 'C:/Users/ad12/Documents/R/win-library/3.5/scamp'
* restoring previous 'C:/Users/ad12/Documents/R/win-library/3.5/scamp'
In R CMD INSTALL
Installation failed: Command failed (1)

**Comment by evangreene** [comment]
Hi Anthony,

Thanks for posting the error messages.

I pushed a change to the repository that should address the specific issue you encountered. When you have a chance, can you try to install the package again? Please let me know if any additional error messages occur.

Thanks,
Evan

**Comment by anthonydevaux** [comment]
Hi Evan,

It works ! Now I have to test it !

Thanks a lot,

Anthony

**Comment by evangreene** [comment]
Hi Anthony,

Glad to hear it worked! 

Please open another issue if any problems come up while using the package. I'm closing this issue as resolved.

Evan
