### ISSUE TITLE
fatal error: sys/resource.h: No such file or directory

### ISSUE THREAD

**Issue by algebio** [RGLab/scamp#3]
Hi 

I'm trying to install FAUST but I'm getting some error messages. I have tried to install scamp only from github, also from source, I have reinstall Rcpp, nothing worked so far.

Any idea of what I could try?

Cheers
Juan

Some details below:

> devtools::install_github("RGLab/scamp")
Downloading GitHub repo RGLab/scamp@master
√  checking for file 'C:\Users\njo47\AppData\Local\Temp\Rtmpkn14Po\remotes331477d76d45\RGLab-scamp-6561eda/DESCRIPTION' (363ms)
-  preparing 'scamp':
√  checking DESCRIPTION meta-information ... 
-  cleaning src
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
-  building 'scamp_0.2.36.tar.gz'
   
Installing package into ‘C:/Users/njo47/R/win-library/3.6’
(as ‘lib’ is unspecified)
* installing *source* package 'scamp' ...
** using staged installation
** libs

*** arch - i386
c:/Rtools/mingw_32/bin/g++  -I"C:/PROGRA~1/R/R-36~1.0/include" -DNDEBUG  -I"C:/Users/njo47/R/win-library/3.6/Rcpp/include"     -std=c++11   -O2 -Wall  -mtune=generic -c RcppExports.cpp -o RcppExports.o
c:/Rtools/mingw_32/bin/g++  -I"C:/PROGRA~1/R/R-36~1.0/include" -DNDEBUG  -I"C:/Users/njo47/R/win-library/3.6/Rcpp/include"     -std=c++11   -O2 -Wall  -mtune=generic -c absSampleLmoments.cpp -o absSampleLmoments.o
absSampleLmoments.cpp: In function 'std::vector<double> absSampleLmoments(std::vector<double>, int, int)':
absSampleLmoments.cpp:75:22: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (auto i = 0; i != tmpDV.size(); ++i) 
                      ^
absSampleLmoments.cpp:83:24: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (auto i = 0; i != legendrePoly.size(); ++i)  {
                        ^
absSampleLmoments.cpp:108:25: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       for (int r = 1; r != (lMoments.size() - 1); ++r) {
                         ^
absSampleLmoments.cpp:116:22: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (auto i = 0; i != lMoments.size(); ++i)
                      ^
c:/Rtools/mingw_32/bin/g++  -I"C:/PROGRA~1/R/R-36~1.0/include" -DNDEBUG  -I"C:/Users/njo47/R/win-library/3.6/Rcpp/include"     -std=c++11   -O2 -Wall  -mtune=generic -c addNoiseToDataMatrix.cpp -o addNoiseToDataMatrix.o
addNoiseToDataMatrix.cpp:24:26: fatal error: sys/resource.h: No such file or directory
 #include <sys/resource.h>
                          ^
compilation terminated.
make: *** [C:/PROGRA~1/R/R-36~1.0/etc/i386/Makeconf:215: addNoiseToDataMatrix.o] Error 1
ERROR: compilation failed for package 'scamp'
* removing 'C:/Users/njo47/R/win-library/3.6/scamp'
Error: Failed to install 'scamp' from GitHub:
  (converted from warning) installation of package ‘C:/Users/njo47/AppData/Local/Temp/Rtmpkn14Po/file3314673169ab/scamp_0.2.36.tar.gz’ had non-zero exit status

> sessionInfo()
R version 3.6.0 (2019-04-26)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 17134)

Matrix products: default

locale:
[1] LC_COLLATE=English_United Kingdom.1252  LC_CTYPE=English_United Kingdom.1252   
[3] LC_MONETARY=English_United Kingdom.1252 LC_NUMERIC=C                           
[5] LC_TIME=English_United Kingdom.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] devtools_2.1.0     usethis_1.5.1      BiocManager_1.30.4

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.2        rstudioapi_0.10   magrittr_1.5      pkgload_1.0.2     R6_2.4.0         
 [6] rlang_0.4.0       tools_3.6.0       pkgbuild_1.0.3    sessioninfo_1.1.1 cli_1.1.0        
[11] withr_2.1.2       remotes_2.1.0     assertthat_0.2.1  digest_0.6.20     rprojroot_1.3-2  
[16] crayon_1.3.4      processx_3.4.0    callr_3.3.0       fs_1.3.1          ps_1.3.0         
[21] curl_3.3          testthat_2.1.1    memoise_1.1.0     glue_1.3.1        compiler_3.6.0   
[26] desc_1.2.0        backports_1.1.4   prettyunits_1.0.2

**Comment by evangreene** [comment]
Hi,

Thanks for filing this issue. I think it is now resolved. Please try re-installing, and let me know if the issue persists.

Thanks,
Evan

**Comment by algebio** [comment]
Solved.

Thank you.
